# Generated by Django 6.0.4 on 2026-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OPEN_BAR', 'Open Bar'), ('CLOSE_BAR', 'Close Bar'), ('OPEN_CASH', 'Open Cash'), ('CLOSE_CASH', 'Close Cash'), ('CANCEL_SALE', 'Cancel Sale'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment')], max_length=40)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
