# Generated by Django 6.0.4 on 2026-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OPEN_BAR', 'Open Bar'), ('CLOSE_BAR', 'Close Bar'), ('OPEN_CASH', 'Open Cash'), ('CLOSE_CASH', 'Close Cash'), ('CANCEL_SALE', 'Cancel Sale'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed')], max_length=40),
        ),
    ]
