# Generated by Django 6.0.4 on 2026-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Stock critico'), ('CASH_DIFFERENCE', 'Diferencia de caja')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('SENT', 'Enviada'), ('RESOLVED', 'Resuelta')], default='OPEN', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_via', models.CharField(blank=True, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(unique=True)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('surcharges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
