# Generated by Django 6.0.4 on 2026-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
