# Generated by Django 6.0.4 on 2026-04-07 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alertevent_dedup_key_alertevent_occurrence_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDispatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WEBHOOK', 'Webhook'), ('EMAIL', 'Email'), ('SLACK', 'Slack'), ('TELEGRAM', 'Telegram')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], max_length=10)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='reports.alertevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
