# Generated by Django 6.0.4 on 2026-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('document_id', models.CharField(blank=True, max_length=50)),
                ('qr_code', models.CharField(max_length=120, unique=True)),
                ('companions_allowed', models.PositiveSmallIntegerField(default=1)),
                ('companions_used', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ENTERED', 'Ingreso'), ('REJECTED', 'Rechazado'), ('NO_SHOW', 'No asistio')], default='PENDING', max_length=12)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
