# Generated by Django 6.0.4 on 2026-04-07 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='guest_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='guests.guestlist'),
        ),
        migrations.AddConstraint(
            model_name='guestlist',
            constraint=models.UniqueConstraint(fields=('name', 'event_date'), name='unique_guest_list_per_event'),
        ),
        migrations.AddConstraint(
            model_name='guestentry',
            constraint=models.UniqueConstraint(fields=('guest_list', 'full_name'), name='unique_guest_per_list'),
        ),
    ]
