# Generated by Django 6.0.4 on 2026-04-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previsualizado'), ('IMPORTED', 'Importado'), ('FAILED', 'Fallido')], default='PREVIEWED', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('guest_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='guests.guestlist')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestImportJobError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='guests.guestimportjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
