# Generated by Django 6.0.4 on 2026-04-07 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barsession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_bar_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barsession',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_bar_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='barsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('bar',), name='unique_open_session_per_bar'),
        ),
    ]
