# Generated by Django 6.0.4 on 2026-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='costing_method',
            field=models.CharField(choices=[('AVG', 'Promedio'), ('FIFO', 'FIFO')], default='AVG', max_length=10),
        ),
    ]
