# Generated by Django 6.0.4 on 2026-04-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='settings_app.bar'),
        ),
    ]
