# Generated by Django 6.0.4 on 2026-04-07 18:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_cashsession_approved_at_cashsession_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
